# Generated by Django 4.2.1 on 2023-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_transaction_status_transaction_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cart_status",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="transaction_item_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
