# Generated by Django 4.2.1 on 2023-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_cart_cart_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="cart_id", field=models.IntegerField(default=1),
        ),
    ]
